version: "3"
services:

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  funktionsql:
    container_name: funktionsql
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - mysql
